FROM golang:1.25-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /stratum-client ./cmd/client

FROM alpine:3.20

WORKDIR /app
COPY --from=builder /stratum-client /app/client

ENTRYPOINT ["/app/client"]
