// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: proto/storage/storage.proto

package storage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WriteBatchRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Puts          []*WriteBatchRequest_PutOp `protobuf:"bytes,1,rep,name=puts,proto3" json:"puts,omitempty"`
	Deletes       [][]byte                   `protobuf:"bytes,2,rep,name=deletes,proto3" json:"deletes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteBatchRequest) Reset() {
	*x = WriteBatchRequest{}
	mi := &file_proto_storage_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteBatchRequest) ProtoMessage() {}

func (x *WriteBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteBatchRequest.ProtoReflect.Descriptor instead.
func (*WriteBatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_storage_storage_proto_rawDescGZIP(), []int{0}
}

func (x *WriteBatchRequest) GetPuts() []*WriteBatchRequest_PutOp {
	if x != nil {
		return x.Puts
	}
	return nil
}

func (x *WriteBatchRequest) GetDeletes() [][]byte {
	if x != nil {
		return x.Deletes
	}
	return nil
}

type WriteBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteBatchResponse) Reset() {
	*x = WriteBatchResponse{}
	mi := &file_proto_storage_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteBatchResponse) ProtoMessage() {}

func (x *WriteBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteBatchResponse.ProtoReflect.Descriptor instead.
func (*WriteBatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_storage_storage_proto_rawDescGZIP(), []int{1}
}

func (x *WriteBatchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // For MVCC snapshot reads
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_storage_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_storage_storage_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *GetRequest) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_proto_storage_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_proto_storage_storage_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type ScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartKey      []byte                 `protobuf:"bytes,1,opt,name=start_key,json=startKey,proto3" json:"start_key,omitempty"`
	EndKey        []byte                 `protobuf:"bytes,2,opt,name=end_key,json=endKey,proto3" json:"end_key,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanRequest) Reset() {
	*x = ScanRequest{}
	mi := &file_proto_storage_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRequest) ProtoMessage() {}

func (x *ScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRequest.ProtoReflect.Descriptor instead.
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return file_proto_storage_storage_proto_rawDescGZIP(), []int{4}
}

func (x *ScanRequest) GetStartKey() []byte {
	if x != nil {
		return x.StartKey
	}
	return nil
}

func (x *ScanRequest) GetEndKey() []byte {
	if x != nil {
		return x.EndKey
	}
	return nil
}

func (x *ScanRequest) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanResponse) Reset() {
	*x = ScanResponse{}
	mi := &file_proto_storage_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResponse) ProtoMessage() {}

func (x *ScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResponse.ProtoReflect.Descriptor instead.
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return file_proto_storage_storage_proto_rawDescGZIP(), []int{5}
}

func (x *ScanResponse) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ScanResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type SnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotRequest) Reset() {
	*x = SnapshotRequest{}
	mi := &file_proto_storage_storage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRequest) ProtoMessage() {}

func (x *SnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_storage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRequest.ProtoReflect.Descriptor instead.
func (*SnapshotRequest) Descriptor() ([]byte, []int) {
	return file_proto_storage_storage_proto_rawDescGZIP(), []int{6}
}

type SnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // Simplistic representation, typically chunked stream for real implementation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotResponse) Reset() {
	*x = SnapshotResponse{}
	mi := &file_proto_storage_storage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotResponse) ProtoMessage() {}

func (x *SnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_storage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotResponse.ProtoReflect.Descriptor instead.
func (*SnapshotResponse) Descriptor() ([]byte, []int) {
	return file_proto_storage_storage_proto_rawDescGZIP(), []int{7}
}

func (x *SnapshotResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type WriteBatchRequest_PutOp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteBatchRequest_PutOp) Reset() {
	*x = WriteBatchRequest_PutOp{}
	mi := &file_proto_storage_storage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteBatchRequest_PutOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteBatchRequest_PutOp) ProtoMessage() {}

func (x *WriteBatchRequest_PutOp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_storage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteBatchRequest_PutOp.ProtoReflect.Descriptor instead.
func (*WriteBatchRequest_PutOp) Descriptor() ([]byte, []int) {
	return file_proto_storage_storage_proto_rawDescGZIP(), []int{0, 0}
}

func (x *WriteBatchRequest_PutOp) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *WriteBatchRequest_PutOp) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_proto_storage_storage_proto protoreflect.FileDescriptor

const file_proto_storage_storage_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/storage/storage.proto\x12\astorage\"\x94\x01\n" +
	"\x11WriteBatchRequest\x124\n" +
	"\x04puts\x18\x01 \x03(\v2 .storage.WriteBatchRequest.PutOpR\x04puts\x12\x18\n" +
	"\adeletes\x18\x02 \x03(\fR\adeletes\x1a/\n" +
	"\x05PutOp\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\".\n" +
	"\x12WriteBatchResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"<\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x04R\ttimestamp\"9\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"a\n" +
	"\vScanRequest\x12\x1b\n" +
	"\tstart_key\x18\x01 \x01(\fR\bstartKey\x12\x17\n" +
	"\aend_key\x18\x02 \x01(\fR\x06endKey\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x04R\ttimestamp\"6\n" +
	"\fScanResponse\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"\x11\n" +
	"\x0fSnapshotRequest\"&\n" +
	"\x10SnapshotResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data2\x88\x02\n" +
	"\rStorageEngine\x12G\n" +
	"\n" +
	"WriteBatch\x12\x1a.storage.WriteBatchRequest\x1a\x1b.storage.WriteBatchResponse\"\x00\x122\n" +
	"\x03Get\x12\x13.storage.GetRequest\x1a\x14.storage.GetResponse\"\x00\x127\n" +
	"\x04Scan\x12\x14.storage.ScanRequest\x1a\x15.storage.ScanResponse\"\x000\x01\x12A\n" +
	"\bSnapshot\x12\x18.storage.SnapshotRequest\x1a\x19.storage.SnapshotResponse\"\x00B+Z)github.com/sagar0x0/stratum/proto/storageb\x06proto3"

var (
	file_proto_storage_storage_proto_rawDescOnce sync.Once
	file_proto_storage_storage_proto_rawDescData []byte
)

func file_proto_storage_storage_proto_rawDescGZIP() []byte {
	file_proto_storage_storage_proto_rawDescOnce.Do(func() {
		file_proto_storage_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_storage_storage_proto_rawDesc), len(file_proto_storage_storage_proto_rawDesc)))
	})
	return file_proto_storage_storage_proto_rawDescData
}

var file_proto_storage_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_storage_storage_proto_goTypes = []any{
	(*WriteBatchRequest)(nil),       // 0: storage.WriteBatchRequest
	(*WriteBatchResponse)(nil),      // 1: storage.WriteBatchResponse
	(*GetRequest)(nil),              // 2: storage.GetRequest
	(*GetResponse)(nil),             // 3: storage.GetResponse
	(*ScanRequest)(nil),             // 4: storage.ScanRequest
	(*ScanResponse)(nil),            // 5: storage.ScanResponse
	(*SnapshotRequest)(nil),         // 6: storage.SnapshotRequest
	(*SnapshotResponse)(nil),        // 7: storage.SnapshotResponse
	(*WriteBatchRequest_PutOp)(nil), // 8: storage.WriteBatchRequest.PutOp
}
var file_proto_storage_storage_proto_depIdxs = []int32{
	8, // 0: storage.WriteBatchRequest.puts:type_name -> storage.WriteBatchRequest.PutOp
	0, // 1: storage.StorageEngine.WriteBatch:input_type -> storage.WriteBatchRequest
	2, // 2: storage.StorageEngine.Get:input_type -> storage.GetRequest
	4, // 3: storage.StorageEngine.Scan:input_type -> storage.ScanRequest
	6, // 4: storage.StorageEngine.Snapshot:input_type -> storage.SnapshotRequest
	1, // 5: storage.StorageEngine.WriteBatch:output_type -> storage.WriteBatchResponse
	3, // 6: storage.StorageEngine.Get:output_type -> storage.GetResponse
	5, // 7: storage.StorageEngine.Scan:output_type -> storage.ScanResponse
	7, // 8: storage.StorageEngine.Snapshot:output_type -> storage.SnapshotResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_storage_storage_proto_init() }
func file_proto_storage_storage_proto_init() {
	if File_proto_storage_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_storage_storage_proto_rawDesc), len(file_proto_storage_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_storage_storage_proto_goTypes,
		DependencyIndexes: file_proto_storage_storage_proto_depIdxs,
		MessageInfos:      file_proto_storage_storage_proto_msgTypes,
	}.Build()
	File_proto_storage_storage_proto = out.File
	file_proto_storage_storage_proto_goTypes = nil
	file_proto_storage_storage_proto_depIdxs = nil
}
